name: Update Basketball News

on:
  schedule:
    - cron: "0 * * * *"  # รันทุกชั่วโมง (UTC)
  workflow_dispatch:  # ให้สามารถรัน workflow ด้วยตัวเองได้

permissions:
  contents: write  # ให้สิทธิ์ push กลับไปที่ repo

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Set Environment Variables
        run: |
          echo "USER_EMAIL=${{ secrets.USER_EMAIL }}" >> $GITHUB_ENV
          echo "USER_USERNAME=${{ secrets.USER_USERNAME }}" >> $GITHUB_ENV
          echo "USER_REPO=${{ secrets.USER_REPO }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> $GITHUB_ENV

      - name: Run script to update news
        run: python news.py

      - name: Commit and Push Changes
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_USERNAME }}"
          git add news.tmp
          git commit -m "Update Basketball News" || exit 0
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ secrets.USER_REPO }}.git || exit 0
